import React, { useState } from 'react';
import Icon from '../components/Icon';

function ScheduleView() {
  const [todos, setTodos] = useState([{ text: 'Complete Algebra: Quadratic Equations', meta: 'Mathematics · 25 min', done: true }, { text: 'Review Newton’s Laws', meta: 'Physics · 15 min', done: true }, { text: 'Read: The Great Gatsby, Ch. 4', meta: 'English Literature · 30 min', done: false }, { text: 'Practice speaking exercises', meta: 'Communication · 20 min', done: false }]);
  const toggleTodo = (index) => setTodos(todos.map((todo, itemIndex) => itemIndex === index ? { ...todo, done: !todo.done } : todo));
  return <section className="workspace-view">
    <div className="welcome-row"><div><span className="section-kicker">PLAN YOUR WEEK</span><h1>My schedule.</h1><p>Stay organized with lessons, classes, and personal goals.</p></div><button className="outline-btn"><span>＋</span> Add task</button></div>
    <div className="schedule-layout"><section className="panel calendar-panel"><div className="panel-heading"><div><h2>September 2026</h2><p>Monday, September 21</p></div><div className="calendar-controls"><button>‹</button><button>›</button></div></div><div className="calendar-week">{['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-days">{Array.from({ length: 35 }, (_, index) => { const day = index - 1; const current = day === 21; const muted = day < 1 || day > 30; return <button className={`${current ? 'current' : ''} ${muted ? 'muted' : ''}`} key={index}>{muted ? (day < 1 ? 31 + day : day - 30) : day}{[3, 8, 14, 21, 24].includes(day) && <i />}</button>; })}</div></section><section className="panel todo-panel"><div className="panel-heading"><div><h2>Today’s to-do list</h2><p>{todos.filter(todo => todo.done).length} of {todos.length} completed</p></div><span className="todo-date">SEP 21</span></div><div className="todo-list">{todos.map((todo, index) => <button className={`todo-item ${todo.done ? 'done' : ''}`} onClick={() => toggleTodo(index)} key={todo.text}><span className="todo-check">{todo.done ? '✓' : ''}</span><span><strong>{todo.text}</strong><small>{todo.meta}</small></span></button>)}</div><div className="todo-progress"><div><span>Daily progress</span><strong>{Math.round(todos.filter(todo => todo.done).length / todos.length * 100)}%</strong></div><div className="progress-bar"><i style={{ width: `${todos.filter(todo => todo.done).length / todos.length * 100}%` }} /></div></div></section></div>
    <section className="panel upcoming-panel"><div className="panel-heading"><div><h2>Upcoming lessons</h2><p>Your next live and scheduled sessions</p></div><button className="text-btn">View all <Icon name="arrow" size={15} /></button></div><div className="upcoming-list"><div><span className="upcoming-time">TODAY · 4:30 PM</span><strong>Introduction to Electromagnetism</strong><small>Physics · Live with Dr. Mehta</small><button>Join lesson</button></div><div><span className="upcoming-time purple-time">WEDNESDAY · 5:00 PM</span><strong>Essay writing workshop</strong><small>English Literature · Group session</small><button className="secondary-join">View details</button></div><div><span className="upcoming-time green-time">FRIDAY · 6:30 PM</span><strong>Weekly AI assessment</strong><small>Mathematics · 20 questions</small><button className="secondary-join">View details</button></div></div></section>
  </section>;
}

export default ScheduleView;
